### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by JakeRe**

### CODE REVIEW

**Comment by JakeRe** [comment]
Obseeving

**Comment by KeaporaTheOwl** [comment]
Played and reviewed.

**Comment by JakeRe** [comment]
**What was your overall impression of the playthrough?**
Very positive, the space was well constructed and stuck to the narrative of a character breaking out of wherever they're stuck was clear, however I would change the lighting to be a more dark color to set up the idea of a "breakout" better.

**Was all the geometry / terrain / set pieces textured or have vertex color painting?**
Yes, all of it has proper texturing and vertex paint. 

**Were you able to get some context about the world through the geometry/terrain, textures and set pieces?**
Yes, it is a science fiction environment lab/ facility

**Was the space properly lit?**
Yes
 
**Did the areas feel spaced out proportionally to the player character?** 
Each of the areas before you got out into the cityscape felt proper, the buildings however felt out of scale. Yet that I attribute to it being a work in progress.

**Was the playthrough functional?** 
Yes, I was able to go through the area without bugs or issues.

**Comment by JakeRe** [comment]
Lukes game

What was your overall impression of the playthrough?
Very positive, the space was well constructed and stuck to the narrative of a character break 

Was all the geometry / terrain / set pieces textured or have vertex color painting?
Yes, all of it has proper texturing and vertex paint

Were you able to get some context about the world through the geometry/terrain, textures and set pieces?
Yes, it is a science fiction environment lab/ facility and based on where you emerge, which is a tube, you are breaking out of it. 

Was the space properly lit?
Yes the sci fi environment was properly lit as there were no places that seemed like they were darker for no reason. 
 
Did the areas feel spaced out proportionally to the player character? 
Each of the areas before you got out into the city scape felt proper, the buildings however felt out of scale. Yet that I attribute to it being a work in progress.

Was the playthrough functional? 
Yes, I was able to go through the area without bugs or issues.

**Comment by KeaporaTheOwl** [comment]
What was your overall impression of the playthrough? Excellent use of space, environment, and lighting.

The areas were nice and open, which prevented confusion. I could figure out the aesthetic very easily and the objects were used rather nicely.

Was all of the geometry/terrain/set pieces textured or have vertex color painting?
All of the objects were textured/painted.

All objects were textured or painted with obvious reasons as to why.

Were you able to get some context about the world through the geometry/terrain, textures and set pieces?
I had a good idea of the setting merely by observing the game space and would feel confident about guessing without direction

Yes. I figured out the sci-fi vibe of the level without any explanation and was able to understand where the story takes place despite the rough draft.

Was the space properly lit?
The lighting was excellent and even helped guide me through the level

Yes. Nothing was too dark or too bright. Everything felt perfectly lit for me to figure out where to go.
Did the areas feel spaced out proportionally to the player character? 
The spacing was excellent and had good flow

Yes. No area felt too tight or too large.

Was the playthrough functional?
Yes! The game ran smoothly and there were no bugs
Yes. No bugs and I was able to play without issue.

**Comment by jadlerfisher** [comment]
Good work, gentlemen.

**Pull request merged**
